### ISSUE TITLE
Refactor App.java

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#122]
The central class of our data-collection tool ([App.java](https://github.com/refactoring-ai/predicting-refactoring-ml/blob/21319e0aaea395b9665d62205fd758cf8fbf59a0/data-collection/src/main/java/refactoringml/App.java#L32)) is literally **one huge method**, containing all the log. I suggest to refactor it:

1. extract methods
2. refactor attributes
3. move methods to utils, if applicable

**Comment by mauricioaniche** [comment]
I agree. But let's first stabilise this version, and make sure there are no
bugs. Once we are sure, refactor it will be easier.
--
Maurício Aniche
Delft University of Technology
http://www.mauricioaniche.com

**Comment by mauricioaniche** [comment]
Indeed, the name of the parameter there is `datasetName` and not `projectName`. Note how the project name is actually extracted from the GitUrl inside `initProject`. Just fixed it.
