### ISSUE TITLE
Suggestions for improving your paper

### ISSUE THREAD

**Issue by aaghamohammadi** [refactoring-ai/predicting-refactoring-ml#130]
Hello,
I read your paper. I hope it will be accepted. I have some suggestions to improve your paper or give you some ideas for future work.

1. You had faced with imbalanced datasets and used undersampling. One way to deal with this problem is to use **an unbiased metric** such as  Matthews Correlation Coefficient (MCC). In software defect prediction we face the same issue. MCC is widely used in software defect prediction.
2. Using **relative** process metrics might help to improve the results. Again, in software defect prediction relative process metrics improve the results (e.g., see the [paper)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.85.7712&rep=rep1&type=pdf).
3. "We use the Min-Max scaler provided by ..." --> It would be better to consider distribution and then apply the scaler (Standard or Min-Max).
4. "Logistic Regression: C (page 5) --> There are two regularization types (norm 1 and norm 2). Which one do you use?

Thanks for your great paper. Good Luck!

**Comment by mauricioaniche** [comment]
Thanks for the suggestions! @jan-gerling will look at it!
