### ISSUE TITLE
Considering files 'Test*' as test files too

### ISSUE THREAD

**Issue by mauricioaniche** [refactoring-ai/predicting-refactoring-ml#146]
Skimming some Apache projects, I found examples of test files that start are like `Test*.java`. IIRC, we only look for _Test_ at the end of the file.

Let's double check.

**Comment by jan-gerling** [comment]
@mauricioaniche can you please give me more details?
I am not facing the described issues:
https://github.com/refactoring-ai/predicting-refactoring-ml/blob/3138bbf16078bf2e2bcec283d8498ac42414d973/data-collection/src/test/java/refactoringml/UtilsTest.java#L47-L49

**Comment by mauricioaniche** [comment]
oh, it's already implemented! Great! Closing this issue!

**Comment by mauricioaniche** [comment]
oh, it's already implemented! Great! Closing this issue!
