### ISSUE TITLE
Model training: use variableAppeareances=-1 or not?

### ISSUE THREAD

**Issue by mauricioaniche** [refactoring-ai/predicting-refactoring-ml#15]
In cases where the variable appeared in the refactoredCommit, we now leave `variableAppeareances = -1`. Before, we used to delete it, but this means we lose a good amount of data points in these refactorings.

We should understand the best way to feed this new number in the model. Maybe feeding -1 to the model is fine?

**Comment by mauricioaniche** [comment]
We need to understand which refactorings actually have a `variableAppeareances = -1`. My guess is that, eg., Extract Variable, as the variable did not exist in the previous version.

In these cases, we should simply drop this column, as it's not a good feature.

**Comment by Dahny** [comment]
I've done some research regarding this matter. Indeed in most cases when there is a `Extract Variable` the `variableAppearance` seems to be -1. But this is in more cases, especially when we have a `Merge Variable`. I ran some tests on a single project (Elasticsearch) where I used the data collection tool on and I ran some test on our test datasets and this is what I got out of them (the amount of times the `variableAppearance = -1`/total amount of appearances:

# ElasticSearch
## ALL Cases
-Extract Variable					1452
-Merge Variable						60
-Rename Variable					3174
-Change Variable Type				8819
-Replace Variable With Attribute	144
-Rename Parameter					3896
Inline Variable						359
Parameterize Variable				132
Split Variable						11


## -1 cases
-Extract Variable					1359
-Merge Variable						60
-Rename Variable					15
-Change Variable Type				241
-Replace Variable With Attribute	7
-Rename Parameter					1


## cases vs total
-Extract Variable					93.6%
-Merge Variable						100%
-Rename Variable					0.47%
-Change Variable Type				2.73%
-Replace Variable With Attribute	4.86%
-Rename Parameter					0.02%

# Test projects
## All Cases
-Extract Variable					176
-Merge Variable						6
-Rename Variable					356
-Change Variable Type				1038
-Rename Parameter					591
Replace Variable With Attribute		27
Parameterize Variable				21
Inline Variable						37
Split Variable						2

## -1 cases
-Extract Variable					175
-Merge Variable						6
-Rename Variable					1
-Change Variable Type				11
-Rename Parameter					1

## cases vs total
-Extract Variable					99.4%
-Merge Variable						100%
-Rename Variable					0.28%
-Change Variable Type				1.05%
-Rename Parameter					0.17%

**Comment by Dahny** [comment]
I am not sure whether we should drop the column or not

**Comment by mauricioaniche** [comment]
Can you show us here a concrete example of a method that has variable appearances = -1 and another one that has variable appearances > -1 ? So that @jan-gerling and I can also see if this is a bug in the data collection tool.

**Comment by jan-gerling** [comment]
@Dahny for the extract Variable refactoring this behavior is expected. The refactoring creates a new variable in order to make the code more readable, thus the newly introduced variable has rarely occurred before. I am not sure about the cases where it actually occurred before.

**Comment by jan-gerling** [comment]
For the Change Variable Type it is a bug here is an example:
https://github.com/apache/commons-csv/commit/aee6c50e2830c007a572cc96a57bc105308acc49#diff-b4b7d49949eefbf1e026ccd68eb5cb3eL192-R220

**Comment by Dahny** [comment]
Merge Variable	(bad case appearance == -1)
https://imgur.com/a/116NbfB
https://github.com/elastic/elasticsearch/commit/6314c2460cc55cba5f7c5c7826b63b4278eaffb1
[lats : double[], lat : double] to docPoint : GeoPoint 
in method public getDocIdSet(reader IndexReader) : DocIdSet 
in class org.elasticsearch.common.lucene.geo.GeoPolygonFilter

Rename Variable	(bad case appearance == -1)
https://imgur.com/a/9sy3c9p
https://github.com/elastic/elasticsearch/commit/8b36281d60350727ac2475f54b32769a84ed863b
result : SearchResponse to response : SearchResponse 
in method public handleRequest(request RestRequest, channel RestChannel) : void 
in class org.elasticsearch.rest.action.search.RestSearchAction

Rename Variable  (good case appearance == 1)
https://imgur.com/a/y29kbDZ
https://github.com/elastic/elasticsearch/commit/2e81730272b35c4754b42c4ecfc0f94757435b9a
shardCountResponse : ShardFlushResponse to shardResponse : Object 
in method protected newResponse(request FlushRequest, shardsResponses AtomicReferenceArray, clusterState ClusterState) : FlushResponse 
in class org.elasticsearch.action.admin.indices.flush.TransportFlushAction

Rename Parameter (bad case appearance == -1)	
https://imgur.com/a/MefTqgl
https://github.com/elastic/elasticsearch/commit/11bafa18e1b1c6d9a95da57295fc9e2271f12ba7
orders : List<Terms.Order> to order : Terms.Order 
in method public order(order Terms.Order) : TermsAggregatorFactory 
in class org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory

Rename Parameter  (good case appearance == 1)
https://imgur.com/a/TVHxZEq
https://github.com/elastic/elasticsearch/commit/14f2445e2a0316f2e5d933e1f3bc4a64c175b565
index : String... to indices : String... 
in method public searchRequest(indices String...) : SearchRequest 
in class org.elasticsearch.client.Requests

Replace Variable With Attribute	(bad case appearance == -1)
https://imgur.com/a/OnrMO5g
https://github.com/elastic/elasticsearch/commit/42e85674778ad1f26695f6c632a0a9fab6f1174c
metaData : MetaData to currentJoinThread : Thread 
in method private asyncJoinCluster() : void 
in class org.elasticsearch.discovery.zen.ZenDiscovery

(With this one I could not find the initial metaData variable?)

Replace Variable With Attribute (bad case appearance == -1)
https://imgur.com/a/bNWGwg1
https://github.com/elastic/elasticsearch/commit/e78e6652731aa5ae460f1e7ff210920e9e570ad1
electedMaster : DiscoveryNode to localNode : DiscoveryNode 
in method private handleMasterGone(masterNode DiscoveryNode, reason String) : void 
in class org.elasticsearch.discovery.zen.ZenDiscovery

Replace Variable With Attribute  (good case appearance == 1)
https://imgur.com/a/QMKBvid
https://github.com/elastic/elasticsearch/commit/f2eae5b6057d562f47768eebade3adcc93326f6a
warmCache : boolean to largeCacheSize : ByteSizeValue 
in method public ByteBufferCache(settings Settings) 
in class org.elasticsearch.cache.memory.ByteBufferCache

**Comment by jan-gerling** [comment]
All faulty process and authorship metrics are removed if required from the ml pipeline, after this pr #169
