### ISSUE TITLE
Improving getReverseWalk

### ISSUE THREAD

**Issue by mauricioaniche** [refactoring-ai/predicting-refactoring-ml#167]
The `getReverseWalk` for now gets all the commits in the order Git returns. This means whenever there's a branch that was merged, we see commits from both paths.

I'd say that's ok in most cases when it comes to the source code metrics. After all, we'll get the version - 1 and Git will return the right before version of the class, as it correctly knows the parent.

However, for process metrics, this can become tricky. As we will count the process metrics (e.g., authors, commits) from both branches... Or maybe that's ok? Well, maybe that's ok... What do you think?

**Comment by jan-gerling** [comment]
This issue will be closed for now.

@jan-gerling 
Future me:
For validation sum up the number of duplicate commits appearing in a small number of repositories , in order to check if this issue leads to double counting of commits.
