### ISSUE TITLE
Model training: ignore process metrics that are -1

### ISSUE THREAD

**Issue by mauricioaniche** [refactoring-ai/predicting-refactoring-ml#18]
We purposely put -1 to process metrics in rare cases, where we can't detect the process metrics of that file before a refactoring has happened.

We still store it in the database, so that we can use that data point for models that rely solely on structural metrics.

**Comment by mauricioaniche** [comment]
Tip: Do not do it in the SQL queries, but later in Pandas (and only if PROCESS_METRICS are taken into account)

**Comment by jan-gerling** [comment]
I will write some tests for the data collection, to identify and understand these cases.
