### ISSUE TITLE
Understand what type of refactorings return two classes

### ISSUE THREAD

**Issue by mauricioaniche** [refactoring-ai/predicting-refactoring-ml#26]
RefactoringMiner might return two classes (instead of one) for some refactorings. See `RefactoringAnalyzer`, more precisely where we call `get...BeforeRefactoring`.

Investigate:
- Which ones do it
- Observe how our tool behaves in such cases
- Write tests for these cases

**Comment by mauricioaniche** [comment]
RefactoringMiner might return more than one refactoring in the list (see `App.java:collectCommitData`, the first for-each loop). 

We should write a test to understand how our system behaves in such case.

Where you can find the refactorings that return more than one? https://github.com/tsantalis/RefactoringMiner/commit/fe423532a8d9f289750b8b45875812a4c9ef3ea2. The `Move Class` refactoring is one of them. Are there more?

**Comment by jan-gerling** [comment]
1. **Variable Declaration (AfterRefactoring)** - src/gr/uom/java/xmi/diff/SplitAttributeRefactoring.java
2. **MovedClassToAnotherSourceFolder** - src/gr/uom/java/xmi/diff/MoveSourceFolderRefactoring.java
3. **Merge Attribute** - src/gr/uom/java/xmi/diff/MergeAttributeRefactoring.java
4.  **Extract Class** - src/gr/uom/java/xmi/diff/ExtractSuperclassRefactoring.java
5. **Move Class** - src/gr/uom/java/xmi/diff/RenamePackageRefactoring.java

**Comment by mauricioaniche** [comment]
- `Rename Package and Move Source Folder`: let's not collect them
- `Extract Superclass / Extract interface`, `Merge attribute` and `SplitAttribute`: Let's collect all data points (@jan-gerling)
- `Merge attribute` and `SplitAttribute`:  move it to 'other refactorings'

**Comment by jan-gerling** [comment]
@Dahny 
Can you please write a test for merge and split attribute in one of the toy projects and add a refactoring to them? Also, could you make sure that the refactorings affect at least two classes? Then we know if our handling of multiple class refactorings works.

**Comment by jan-gerling** [comment]
> * `Rename Package and Move Source Folder`: let's not collect them
> * `Extract Superclass / Extract interface`, `Merge attribute` and `SplitAttribute`: Let's collect all data points (@jan-gerling)
> * `Merge attribute` and `SplitAttribute`:  move it to 'other refactorings'

If we don't collect the Rename Package and Move Source Folder refactorings, then we get issues with the Process Metrics tracking, because the class files are not updated to a new file path. Furthermore, this will also create issues with saving the source code of stable commits.

**Comment by jan-gerling** [comment]
We already collect all metrics for refactorings affecting multiple "from" classes:
https://github.com/mauricioaniche/predicting-refactoring-ml/blob/bff25d32fddec48527fa5dfe7b90a68dd6450164/data-collection/src/main/java/refactoringml/RefactoringAnalyzer.java#L63

**Comment by mauricioaniche** [comment]
See the discussion in https://github.com/tsantalis/RefactoringMiner/issues/87

`Move and Inline` now returns two files. `Extract and Move Method` will also return two files.

**Comment by mauricioaniche** [comment]
There won't be a way to know which one is the origin and which one is the destination (see final comments in #87).

We should implement a way to do this, maybe by parsing the refactoring description.

TBH, right now, as we try both files, one of them will fail because the origin method doesn't exist in the destination method. So, we collect the data we want, but we have some noise in the logs, which is not nice. Fix it? Let it go? Suggestions?

**Comment by jan-gerling** [comment]
> There won't be a way to know which one is the origin and which one is the destination (see final comments in #87).
> 
> We should implement a way to do this, maybe by parsing the refactoring description.
> 
> TBH, right now, as we try both files, one of them will fail because the origin method doesn't exist in the destination method. So, we collect the data we want, but we have some noise in the logs, which is not nice. Fix it? Let it go? Suggestions?

We could try the String parsing, it is not too difficult.

**Comment by mauricioaniche** [comment]
Closing it again, fixed by #128
