### ISSUE TITLE
Use the new version of CK

### ISSUE THREAD

**Issue by mauricioaniche** [refactoring-ai/predicting-refactoring-ml#42]
... that I will release soon.

**Comment by mauricioaniche** [comment]
@Dahny, I just release CK 0.5.0. Feel free to update it in the project!

 There might be a small breaking change. The _subClass_ getter is now called _innerClass_. Should be an easy fix in our code. See https://github.com/mauricioaniche/ck/issues/38

**Comment by jan-gerling** [comment]
@Dahny when can you add the new version of CK?
It would be great to integrate it, before running the first large scale test.

**Comment by Dahny** [comment]
Most likely today
