### ISSUE TITLE
NumberOfProductionFiles counted incorrectly - Minor Bug

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#51]
## Problem:
The `project.getNumberOfProductionFiles()` in the metrics Test **returns 4** in the [R2ToyProjectTest.java](https://github.com/mauricioaniche/predicting-refactoring-ml/blob/181dd7bf8c66493c4e4cd492ded54664b04d311f/data-collection/src/test/java/integration/toyprojects/R2ToyProjectTest.java) even though we **expect 3**.

## Reason:
unknown

**Comment by mauricioaniche** [comment]
The difference is small when we run on Windows, so we can close it for now.
