### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#75]
I noticed that the data-collection could be faster, with some tweaks and optimizations.
Please add all potential optimizations here.

**Comment by jan-gerling** [comment]
Currently, for every commit, we evaluate against the entire PMTrackerDatabase in order to figure out if any of the Instances we store is stable. This is very inefficient, especially, if we move the PMDatabase from in-memory to an SQL database.

It is not necessary to evaluate against the entire PMTrackerDatabase, but only the class files that were changed in the current commit.

**Comment by jan-gerling** [comment]
> Currently, for every commit, we evaluate against the entire PMTrackerDatabase in order to figure out if any of the Instances we store is stable. This is very inefficient, especially, if we move the PMDatabase from in-memory to an SQL database.
> 
> It is not necessary to evaluate against the entire PMTrackerDatabase, but only the class files that were changed in the current commit.

Opened a PR #77 for this.

**Comment by jan-gerling** [comment]
In the RefactoringAnalyzer we store the source code in a tempdir, analyze it, remove it and then eventually store it again:
https://github.com/refactoring-ai/predicting-refactoring-ml/blob/492fc89f922a32791f60a69586274a35aa58a0be/data-collection/src/main/java/refactoringml/RefactoringAnalyzer.java#L100-L127

We can only remove the source in case we don't store it, we then can save lots of writes.

**Comment by mauricioaniche** [comment]
We are happy with performance right now.
