### ISSUE TITLE
Queue returns projects that were already processed.

### ISSUE THREAD

**Issue by jan-gerling** [refactoring-ai/predicting-refactoring-ml#98]
In the #95 a common bug was the retry of already processed projects because they were given by the queue.

**Comment by jan-gerling** [comment]
Probably an explanation:
RabbitMQ will redeliver a message if the client unexpectedly quits and did not acknowledge the first delivery. https://www.rabbitmq.com/tutorials/tutorial-two-python.html

Maybe, the client fails (e.g. with a HeapSpace Error) and then gets the same message over and over again, because it fails to process the already processed repo.

**Comment by mauricioaniche** [comment]
How do we always acknowledge the receive before processing the project? I thought this was done by the `basicGet` method already.
